# Generated by Django 2.2.4 on 2020-07-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='meal_number',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
